# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push.
on:
  push:
    branches: [ staging ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  submodules_sync:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checkout parent repo
    - name: Checkout parent repo
      uses: actions/checkout@v2
      with:
        repository: gonzalomass/parent
        ref: staging
        token: ${{ secrets.PAT }}
        path: main
        submodules: true
    
    # Update submodule
    - name: Update submodule
      run: |
        git config --global user.name github-actions
        git config --global user.email github-actions@github.com
        cd main/sub
        git remote update
        git fetch
        git checkout -b staging
        git pull origin staging --rebase
        cd ..
        git add sub
        git commit -m github.event.head_commit.message
        git push
