name: Staging CD to parent

on:
  push:
    branches: [ staging ]

jobs:
  staging_cd_to_parent:
    runs-on: ubuntu-latest
    steps:
    # Checkout parent repo
    - name: Checkout parent repo
      uses: actions/checkout@v2
      with:
        repository: gonzalomass/parent
        ref: staging
        token: ${{ secrets.PAT }}
        path: main
        submodules: true

    # Update submodule
    - name: Update submodule
      run: |
        git config --global user.name github-actions
        git config --global user.email github-actions@github.com
        gh auth login --with-token < ${{ secrets.PAT }}
        cd main/sub
        git remote update
        git fetch
        git checkout -b staging
        git pull origin staging --rebase
        git checkout -b staging-sub-update
        git pull origin staging --rebase
        cd ..
        git add sub
        git commit -m "${{ github.event.head_commit.message }}"
        git push
        gh pr create -B staging -f -l automerge
        gh pr merge staging-sub-update -m
