name: Staging CD to parent

on:
  push:
    branches: [ staging ]

jobs:
  staging_cd_to_parent:
    runs-on: ubuntu-latest
    steps:
    # Checkout parent repo
    - name: Checkout parent repo
      uses: actions/checkout@v2
      with:
        repository: gonzalomass/parent
        ref: staging
        token: ${{ secrets.PAT }}
        path: main
        submodules: true

    - name : GITHUB CONTEXT
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: echo "$GITHUB_CONTEXT"

    # Update submodule
    - name: Update submodule
      run: |
        echo "$GITHUB_CONTEXT"
        git config --global user.name github-actions
        git config --global user.email github-actions@github.com
        echo -n ${{ secrets.PAT }} >> token.txt
        gh auth login --with-token < token.txt
        rm token.txt
        cd main/sub
        git remote update
        git fetch
        git checkout -b staging
        git pull origin staging --rebase
        cd ..
        git add sub
        git commit --author="${{ github.event.head_commit.author.username }} <${{ github.event.head_commit.author.email }}>" -m "${{ github.event.head_commit.message }}"
        git checkout -b staging-sub-update
        git push origin staging-sub-update:staging-sub-update
        gh pr create -B staging -a ${{ github.event.head_commit.author.username }} -t "update at ${{ github.repository }} by ${{ github.actor }}" -b "${{ github.event.head_commit.message }}"
        git fetch
        gh pr status
        TIMEOUT=0
        until [ $TIMEOUT -eq 60 ] || gh pr status | grep -A2 "Current branch" | tail -n1 | grep -q "passing" || gh pr status | grep -A2 "Current branch" | tail -n1 | grep -q "failing"
        do
          sleep 1
          echo $((TIMEOUT++))
        done
        if gh pr status | grep -A2 "Current branch" | tail -n1 | grep -q "passing";
        then
          echo "checks passing" ;
          gh pr merge staging-sub-update -m
        else
          gh pr close staging-sub-update -d
          echo "checks failing, not present or timeout" ; exit 2 ;
        fi
