name: Staging CI

on:
  pull_request:
    branches: [ staging ]

jobs:
  staging_ci:
    runs-on: ubuntu-latest
    steps:
    # Checkout your repository under $GITHUB_WORKSPACE
    - uses: actions/checkout@v2

    # Runs a set of commands using the runners shell
    - name: Run a multi-line script
      run: |
        npm install
        npm run build
