name: Staging CI

on:
  pull_request:
    branches: [ staging ]

jobs:
  staging_ci:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run a front-end build
      run: |
        npm install
        npm run build
