name: Tag

on:
  push:
    branches: [ master ]

  workflow_dispatch:

jobs:
  tag:
    name: Tag
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: '0'

      - name: Bump tag
        id: bump_tag
        uses: anothrNick/github-tag-action@1.26.0
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
          WITH_V: true

      - name: Update readme
        - uses: pocket-apps/action-update-version@v1
          with:
            files: 'README.md'
            version-regexp: '\d+.\d+.\d+'
            repo-token: ${{ secrets.PAT }}
