name: Tag

on:
  push:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    name: Tag
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: '0'

      - name: Bump version and push tag
        id: bump_tag
        uses: anothrNick/github-tag-action@1.26.0
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
          WITH_V: true
