name: Tag

on:
  push:
    branches: [ master ]

  workflow_dispatch:

jobs:
  tag:
    name: Tag
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: '0'

      - name: Bump tag
        id: bump_tag
        uses: hennejg/github-tag-action@v4.1.jh1
        with:
          github_token: ${{ secrets.PAT }}
